// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_queries.sql

package sqlc

import (
	"context"
	"time"
)

const create = `-- name: Create :one
INSERT INTO users (email, password)
VALUES ($1, $2)
RETURNING user_id, email, role, created_at
`

type CreateParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateRow struct {
	UserID    int64     `json:"user_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

// Inserts a new user
func (q *Queries) Create(ctx context.Context, arg CreateParams) (CreateRow, error) {
	row := q.db.QueryRow(ctx, create, arg.Email, arg.Password)
	var i CreateRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const findByEmail = `-- name: FindByEmail :one
SELECT user_id, email, password, role, created_at 
FROM users 
WHERE email = $1
`

type FindByEmailRow struct {
	UserID    int64     `json:"user_id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

// Finds a user by email
func (q *Queries) FindByEmail(ctx context.Context, email string) (FindByEmailRow, error) {
	row := q.db.QueryRow(ctx, findByEmail, email)
	var i FindByEmailRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const findByID = `-- name: FindByID :one
SELECT user_id, email, role, created_at 
FROM users 
WHERE user_id = $1
`

type FindByIDRow struct {
	UserID    int64     `json:"user_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

// Finds a user by ID
func (q *Queries) FindByID(ctx context.Context, userID int64) (FindByIDRow, error) {
	row := q.db.QueryRow(ctx, findByID, userID)
	var i FindByIDRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
