// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFood = `-- name: CreateFood :one
INSERT INTO food(user_id,food_name,calories_100,protein_100,carbs_100,fats_100)
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING food_id,food_name,calories_100,protein_100,carbs_100,fats_100
`

type CreateFoodParams struct {
	UserID      pgtype.Int4    `json:"user_id"`
	FoodName    string         `json:"food_name"`
	Calories100 pgtype.Numeric `json:"calories_100"`
	Protein100  pgtype.Numeric `json:"protein_100"`
	Carbs100    pgtype.Numeric `json:"carbs_100"`
	Fats100     pgtype.Numeric `json:"fats_100"`
}

type CreateFoodRow struct {
	FoodID      int32          `json:"food_id"`
	FoodName    string         `json:"food_name"`
	Calories100 pgtype.Numeric `json:"calories_100"`
	Protein100  pgtype.Numeric `json:"protein_100"`
	Carbs100    pgtype.Numeric `json:"carbs_100"`
	Fats100     pgtype.Numeric `json:"fats_100"`
}

// Creates a food item
func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (CreateFoodRow, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.UserID,
		arg.FoodName,
		arg.Calories100,
		arg.Protein100,
		arg.Carbs100,
		arg.Fats100,
	)
	var i CreateFoodRow
	err := row.Scan(
		&i.FoodID,
		&i.FoodName,
		&i.Calories100,
		&i.Protein100,
		&i.Carbs100,
		&i.Fats100,
	)
	return i, err
}

const deleteFoodById = `-- name: DeleteFoodById :exec
DELETE FROM food
WHERE food_id = $1 AND user_id = $2
`

type DeleteFoodByIdParams struct {
	FoodID int32       `json:"food_id"`
	UserID pgtype.Int4 `json:"user_id"`
}

// Removes a particular food item (by ID)
func (q *Queries) DeleteFoodById(ctx context.Context, arg DeleteFoodByIdParams) error {
	_, err := q.db.Exec(ctx, deleteFoodById, arg.FoodID, arg.UserID)
	return err
}

const logFood = `-- name: LogFood :one
INSERT INTO food_entries(user_id,food_id,calories,total_grams,protein,carbs,fats)
VALUES ($1,$2,$3,$4,$5,$6,$7)
RETURNING food_entries_id,calories,total_grams,protein,carbs,fats
`

type LogFoodParams struct {
	UserID     int32          `json:"user_id"`
	FoodID     pgtype.Int4    `json:"food_id"`
	Calories   pgtype.Numeric `json:"calories"`
	TotalGrams pgtype.Numeric `json:"total_grams"`
	Protein    pgtype.Numeric `json:"protein"`
	Carbs      pgtype.Numeric `json:"carbs"`
	Fats       pgtype.Numeric `json:"fats"`
}

type LogFoodRow struct {
	FoodEntriesID int32          `json:"food_entries_id"`
	Calories      pgtype.Numeric `json:"calories"`
	TotalGrams    pgtype.Numeric `json:"total_grams"`
	Protein       pgtype.Numeric `json:"protein"`
	Carbs         pgtype.Numeric `json:"carbs"`
	Fats          pgtype.Numeric `json:"fats"`
}

// Logs a particular food eaten
func (q *Queries) LogFood(ctx context.Context, arg LogFoodParams) (LogFoodRow, error) {
	row := q.db.QueryRow(ctx, logFood,
		arg.UserID,
		arg.FoodID,
		arg.Calories,
		arg.TotalGrams,
		arg.Protein,
		arg.Carbs,
		arg.Fats,
	)
	var i LogFoodRow
	err := row.Scan(
		&i.FoodEntriesID,
		&i.Calories,
		&i.TotalGrams,
		&i.Protein,
		&i.Carbs,
		&i.Fats,
	)
	return i, err
}

const viewFoodsByUser = `-- name: ViewFoodsByUser :many
SELECT food_id, food_name, calories_100, protein_100, carbs_100, fats_100, created_at
FROM food
WHERE user_id = $1
ORDER BY created_at DESC
`

type ViewFoodsByUserRow struct {
	FoodID      int32            `json:"food_id"`
	FoodName    string           `json:"food_name"`
	Calories100 pgtype.Numeric   `json:"calories_100"`
	Protein100  pgtype.Numeric   `json:"protein_100"`
	Carbs100    pgtype.Numeric   `json:"carbs_100"`
	Fats100     pgtype.Numeric   `json:"fats_100"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

// Views all the foods associated with a user
func (q *Queries) ViewFoodsByUser(ctx context.Context, userID pgtype.Int4) ([]ViewFoodsByUserRow, error) {
	rows, err := q.db.Query(ctx, viewFoodsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViewFoodsByUserRow{}
	for rows.Next() {
		var i ViewFoodsByUserRow
		if err := rows.Scan(
			&i.FoodID,
			&i.FoodName,
			&i.Calories100,
			&i.Protein100,
			&i.Carbs100,
			&i.Fats100,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
