// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Food struct {
	FoodID      int32            `json:"food_id"`
	UserID      pgtype.Int4      `json:"user_id"`
	FoodName    string           `json:"food_name"`
	Calories100 pgtype.Numeric   `json:"calories_100"`
	Protein100  pgtype.Numeric   `json:"protein_100"`
	Carbs100    pgtype.Numeric   `json:"carbs_100"`
	Fats100     pgtype.Numeric   `json:"fats_100"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}

type FoodEntry struct {
	FoodEntriesID int32            `json:"food_entries_id"`
	UserID        int32            `json:"user_id"`
	FoodID        pgtype.Int4      `json:"food_id"`
	Calories      pgtype.Numeric   `json:"calories"`
	TotalGrams    pgtype.Numeric   `json:"total_grams"`
	Protein       pgtype.Numeric   `json:"protein"`
	Carbs         pgtype.Numeric   `json:"carbs"`
	Fats          pgtype.Numeric   `json:"fats"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	LastUpdated   pgtype.Timestamp `json:"last_updated"`
}

type Recipe struct {
	RecipeID     int32            `json:"recipe_id"`
	UserID       pgtype.Int4      `json:"user_id"`
	RecipeName   string           `json:"recipe_name"`
	Instructions pgtype.Text      `json:"instructions"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	LastUpdated  pgtype.Timestamp `json:"last_updated"`
}

type RecipeIngredient struct {
	IngredientID int32            `json:"ingredient_id"`
	RecipeID     int32            `json:"recipe_id"`
	FoodID       int32            `json:"food_id"`
	TotalGrams   pgtype.Numeric   `json:"total_grams"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	LastUpdated  pgtype.Timestamp `json:"last_updated"`
}

type User struct {
	UserID    int64     `json:"user_id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UsersProfile struct {
	UserID      int32            `json:"user_id"`
	DateOfBirth pgtype.Date      `json:"date_of_birth"`
	Height      pgtype.Numeric   `json:"height"`
	Weight      pgtype.Numeric   `json:"weight"`
	IsTrainer   bool             `json:"is_trainer"`
	LastUpdated pgtype.Timestamp `json:"last_updated"`
}
