// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Inserts a new user
	Create(ctx context.Context, arg CreateParams) (CreateRow, error)
	// Creates a food item
	CreateFood(ctx context.Context, arg CreateFoodParams) (CreateFoodRow, error)
	// Removes a particular food item (by ID)
	DeleteFoodById(ctx context.Context, arg DeleteFoodByIdParams) error
	// Finds a user by email
	FindByEmail(ctx context.Context, email string) (FindByEmailRow, error)
	// Finds a user by ID
	FindByID(ctx context.Context, userID int64) (FindByIDRow, error)
	// Logs a particular food eaten
	LogFood(ctx context.Context, arg LogFoodParams) (LogFoodRow, error)
	// Views all the foods associated with a user
	ViewFoodsByUser(ctx context.Context, userID pgtype.Int4) ([]ViewFoodsByUserRow, error)
}

var _ Querier = (*Queries)(nil)
