// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: food.sql

package db

import (
	"context"
)

const createFood = `-- name: CreateFood :one
INSERT INTO food (user_id, name, calories_100, protein_100, carbohydrates_100, fat_100)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, calories_100, protein_100, carbohydrates_100, fat_100, created_at, updated_at
`

type CreateFoodParams struct {
	UserID           string  `json:"user_id"`
	Name             string  `json:"name"`
	Calories100      float64 `json:"calories_100"`
	Protein100       float64 `json:"protein_100"`
	Carbohydrates100 float64 `json:"carbohydrates_100"`
	Fat100           float64 `json:"fat_100"`
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.UserID,
		arg.Name,
		arg.Calories100,
		arg.Protein100,
		arg.Carbohydrates100,
		arg.Fat100,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Calories100,
		&i.Protein100,
		&i.Carbohydrates100,
		&i.Fat100,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :exec
DELETE FROM food
WHERE id = $1 AND user_id = $2
`

type DeleteFoodParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteFood(ctx context.Context, arg DeleteFoodParams) error {
	_, err := q.db.Exec(ctx, deleteFood, arg.ID, arg.UserID)
	return err
}

const getFoodByID = `-- name: GetFoodByID :one
SELECT id, user_id, name, calories_100, protein_100, carbohydrates_100, fat_100, created_at, updated_at FROM food
WHERE id = $1 AND user_id = $2
`

type GetFoodByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetFoodByID(ctx context.Context, arg GetFoodByIDParams) (Food, error) {
	row := q.db.QueryRow(ctx, getFoodByID, arg.ID, arg.UserID)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Calories100,
		&i.Protein100,
		&i.Carbohydrates100,
		&i.Fat100,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoods = `-- name: ListFoods :many
SELECT id, user_id, name, calories_100, protein_100, carbohydrates_100, fat_100, created_at, updated_at FROM food
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFoods(ctx context.Context, userID string) ([]Food, error) {
	rows, err := q.db.Query(ctx, listFoods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Calories100,
			&i.Protein100,
			&i.Carbohydrates100,
			&i.Fat100,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFood = `-- name: UpdateFood :one
UPDATE food
SET name              = $3,
    calories_100      = $4,
    protein_100       = $5,
    carbohydrates_100 = $6,
    fat_100           = $7,
    updated_at        = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, calories_100, protein_100, carbohydrates_100, fat_100, created_at, updated_at
`

type UpdateFoodParams struct {
	ID               string  `json:"id"`
	UserID           string  `json:"user_id"`
	Name             string  `json:"name"`
	Calories100      float64 `json:"calories_100"`
	Protein100       float64 `json:"protein_100"`
	Carbohydrates100 float64 `json:"carbohydrates_100"`
	Fat100           float64 `json:"fat_100"`
}

func (q *Queries) UpdateFood(ctx context.Context, arg UpdateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, updateFood,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Calories100,
		arg.Protein100,
		arg.Carbohydrates100,
		arg.Fat100,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Calories100,
		&i.Protein100,
		&i.Carbohydrates100,
		&i.Fat100,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
