// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meal.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFoodConsumed = `-- name: CreateFoodConsumed :one
INSERT INTO food_consumed (user_id, meal_id, food_id, weight_g,
                           total_calories, total_protein, total_carbohydrates, total_fat)
SELECT $1::uuid,
       $2::uuid,
       f.id,
       $3::float8,
       ($3::float8 / 100) * f.calories_100,
       ($3::float8 / 100) * f.protein_100,
       ($3::float8 / 100) * f.carbohydrates_100,
       ($3::float8 / 100) * f.fat_100
FROM food f
WHERE f.id = $4::uuid
RETURNING id, user_id, meal_id, food_id, weight_g, total_calories, total_protein, total_carbohydrates, total_fat, created_at, updated_at
`

type CreateFoodConsumedParams struct {
	UserID  string  `json:"user_id"`
	MealID  string  `json:"meal_id"`
	WeightG float64 `json:"weight_g"`
	FoodID  string  `json:"food_id"`
}

func (q *Queries) CreateFoodConsumed(ctx context.Context, arg CreateFoodConsumedParams) (FoodConsumed, error) {
	row := q.db.QueryRow(ctx, createFoodConsumed,
		arg.UserID,
		arg.MealID,
		arg.WeightG,
		arg.FoodID,
	)
	var i FoodConsumed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MealID,
		&i.FoodID,
		&i.WeightG,
		&i.TotalCalories,
		&i.TotalProtein,
		&i.TotalCarbohydrates,
		&i.TotalFat,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMeal = `-- name: CreateMeal :one
INSERT INTO meal (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateMealParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal, arg.UserID, arg.Name)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :execrows
WITH deleted_foods AS (
    DELETE FROM food_consumed
    WHERE meal_id = $1::uuid AND user_id = $2::uuid
)
DELETE FROM meal
WHERE id = $1::uuid AND user_id = $2::uuid
`

type DeleteMealParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMeal, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMealByID = `-- name: GetMealByID :one
SELECT m.id, m.user_id, m.name, m.created_at, m.updated_at,
       coalesce(sum(fc.total_calories), 0)::float8      AS total_calories,
       coalesce(sum(fc.total_protein), 0)::float8       AS total_protein,
       coalesce(sum(fc.total_carbohydrates), 0)::float8 AS total_carbohydrates,
       coalesce(sum(fc.total_fat), 0)::float8           AS total_fat
FROM meal m
LEFT JOIN food_consumed fc ON fc.meal_id = m.id
WHERE m.id = $1 AND m.user_id = $2
GROUP BY m.id
`

type GetMealByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type GetMealByIDRow struct {
	ID                 string    `json:"id"`
	UserID             string    `json:"user_id"`
	Name               string    `json:"name"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	TotalCalories      float64   `json:"total_calories"`
	TotalProtein       float64   `json:"total_protein"`
	TotalCarbohydrates float64   `json:"total_carbohydrates"`
	TotalFat           float64   `json:"total_fat"`
}

func (q *Queries) GetMealByID(ctx context.Context, arg GetMealByIDParams) (GetMealByIDRow, error) {
	row := q.db.QueryRow(ctx, getMealByID, arg.ID, arg.UserID)
	var i GetMealByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalCalories,
		&i.TotalProtein,
		&i.TotalCarbohydrates,
		&i.TotalFat,
	)
	return i, err
}

const listFoodConsumedByMeal = `-- name: ListFoodConsumedByMeal :many
SELECT fc.id,
       fc.food_id,
       fc.weight_g,
       fc.total_calories,
       fc.total_protein,
       fc.total_carbohydrates,
       fc.total_fat,
       f.name AS food_name
FROM food_consumed fc
JOIN food f ON f.id = fc.food_id
WHERE fc.meal_id = $1 AND fc.user_id = $2
ORDER BY fc.created_at
`

type ListFoodConsumedByMealParams struct {
	MealID string `json:"meal_id"`
	UserID string `json:"user_id"`
}

type ListFoodConsumedByMealRow struct {
	ID                 string  `json:"id"`
	FoodID             string  `json:"food_id"`
	WeightG            float64 `json:"weight_g"`
	TotalCalories      float64 `json:"total_calories"`
	TotalProtein       float64 `json:"total_protein"`
	TotalCarbohydrates float64 `json:"total_carbohydrates"`
	TotalFat           float64 `json:"total_fat"`
	FoodName           string  `json:"food_name"`
}

func (q *Queries) ListFoodConsumedByMeal(ctx context.Context, arg ListFoodConsumedByMealParams) ([]ListFoodConsumedByMealRow, error) {
	rows, err := q.db.Query(ctx, listFoodConsumedByMeal, arg.MealID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFoodConsumedByMealRow
	for rows.Next() {
		var i ListFoodConsumedByMealRow
		if err := rows.Scan(
			&i.ID,
			&i.FoodID,
			&i.WeightG,
			&i.TotalCalories,
			&i.TotalProtein,
			&i.TotalCarbohydrates,
			&i.TotalFat,
			&i.FoodName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMeals = `-- name: ListMeals :many
SELECT m.id, m.user_id, m.name, m.created_at, m.updated_at,
       coalesce(sum(fc.total_calories), 0)::float8      AS total_calories,
       coalesce(sum(fc.total_protein), 0)::float8       AS total_protein,
       coalesce(sum(fc.total_carbohydrates), 0)::float8 AS total_carbohydrates,
       coalesce(sum(fc.total_fat), 0)::float8           AS total_fat
FROM meal m
LEFT JOIN food_consumed fc ON fc.meal_id = m.id
WHERE m.user_id = $1
GROUP BY m.id
ORDER BY m.created_at DESC
`

type ListMealsRow struct {
	ID                 string    `json:"id"`
	UserID             string    `json:"user_id"`
	Name               string    `json:"name"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	TotalCalories      float64   `json:"total_calories"`
	TotalProtein       float64   `json:"total_protein"`
	TotalCarbohydrates float64   `json:"total_carbohydrates"`
	TotalFat           float64   `json:"total_fat"`
}

func (q *Queries) ListMeals(ctx context.Context, userID string) ([]ListMealsRow, error) {
	rows, err := q.db.Query(ctx, listMeals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealsRow
	for rows.Next() {
		var i ListMealsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCalories,
			&i.TotalProtein,
			&i.TotalCarbohydrates,
			&i.TotalFat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsByDateRange = `-- name: ListMealsByDateRange :many
SELECT m.id, m.user_id, m.name, m.created_at, m.updated_at,
       coalesce(sum(fc.total_calories), 0)::float8      AS total_calories,
       coalesce(sum(fc.total_protein), 0)::float8       AS total_protein,
       coalesce(sum(fc.total_carbohydrates), 0)::float8 AS total_carbohydrates,
       coalesce(sum(fc.total_fat), 0)::float8           AS total_fat
FROM meal m
LEFT JOIN food_consumed fc ON fc.meal_id = m.id
WHERE m.user_id = $1
  AND m.created_at::date BETWEEN $2::date AND $3::date
GROUP BY m.id
ORDER BY m.created_at DESC
`

type ListMealsByDateRangeParams struct {
	UserID   string      `json:"user_id"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

type ListMealsByDateRangeRow struct {
	ID                 string    `json:"id"`
	UserID             string    `json:"user_id"`
	Name               string    `json:"name"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	TotalCalories      float64   `json:"total_calories"`
	TotalProtein       float64   `json:"total_protein"`
	TotalCarbohydrates float64   `json:"total_carbohydrates"`
	TotalFat           float64   `json:"total_fat"`
}

func (q *Queries) ListMealsByDateRange(ctx context.Context, arg ListMealsByDateRangeParams) ([]ListMealsByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listMealsByDateRange, arg.UserID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMealsByDateRangeRow
	for rows.Next() {
		var i ListMealsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCalories,
			&i.TotalProtein,
			&i.TotalCarbohydrates,
			&i.TotalFat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
