// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID        string    `json:"id"`
	WorkoutID string    `json:"workout_id"`
	Name      string    `json:"name"`
	WeightKg  float64   `json:"weight_kg"`
	Reps      int32     `json:"reps"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Food struct {
	ID               string    `json:"id"`
	Name             string    `json:"name"`
	Calories100      float64   `json:"calories_100"`
	Protein100       float64   `json:"protein_100"`
	Carbohydrates100 float64   `json:"carbohydrates_100"`
	Fat100           float64   `json:"fat_100"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type FoodConsumed struct {
	ID                 string    `json:"id"`
	UserID             string    `json:"user_id"`
	MealID             string    `json:"meal_id"`
	FoodID             string    `json:"food_id"`
	WeightG            float64   `json:"weight_g"`
	TotalCalories      float64   `json:"total_calories"`
	TotalProtein       float64   `json:"total_protein"`
	TotalCarbohydrates float64   `json:"total_carbohydrates"`
	TotalFat           float64   `json:"total_fat"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type Meal struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Recipe struct {
	ID        string      `json:"id"`
	UserID    string      `json:"user_id"`
	Name      string      `json:"name"`
	Notes     pgtype.Text `json:"notes"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type RecipeIngredient struct {
	ID        string      `json:"id"`
	RecipeID  string      `json:"recipe_id"`
	FoodID    string      `json:"food_id"`
	WeightG   float64     `json:"weight_g"`
	Notes     pgtype.Text `json:"notes"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserProfile struct {
	ID          string        `json:"id"`
	UserID      string        `json:"user_id"`
	FirstName   pgtype.Text   `json:"first_name"`
	LastName    pgtype.Text   `json:"last_name"`
	DateOfBirth pgtype.Date   `json:"date_of_birth"`
	HeightCm    pgtype.Float8 `json:"height_cm"`
	WeightKg    pgtype.Float8 `json:"weight_kg"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type Workout struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
