// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipe.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipe (user_id, name, notes)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, notes, created_at, updated_at
`

type CreateRecipeParams struct {
	UserID string      `json:"user_id"`
	Name   string      `json:"name"`
	Notes  pgtype.Text `json:"notes"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe, arg.UserID, arg.Name, arg.Notes)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecipeIngredient = `-- name: CreateRecipeIngredient :one
INSERT INTO recipe_ingredients (recipe_id, food_id, weight_g, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, recipe_id, food_id, weight_g, notes, created_at, updated_at
`

type CreateRecipeIngredientParams struct {
	RecipeID string      `json:"recipe_id"`
	FoodID   string      `json:"food_id"`
	WeightG  float64     `json:"weight_g"`
	Notes    pgtype.Text `json:"notes"`
}

func (q *Queries) CreateRecipeIngredient(ctx context.Context, arg CreateRecipeIngredientParams) (RecipeIngredient, error) {
	row := q.db.QueryRow(ctx, createRecipeIngredient,
		arg.RecipeID,
		arg.FoodID,
		arg.WeightG,
		arg.Notes,
	)
	var i RecipeIngredient
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.FoodID,
		&i.WeightG,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :execrows
WITH deleted_ingredients AS (
    DELETE FROM recipe_ingredients
    WHERE recipe_id = $1::uuid
      AND EXISTS (
          SELECT 1 FROM recipe r
          WHERE r.id = $1::uuid AND r.user_id = $2::uuid
      )
)
DELETE FROM recipe
WHERE id = $1::uuid AND user_id = $2::uuid
`

type DeleteRecipeParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteRecipe(ctx context.Context, arg DeleteRecipeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecipe, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecipeIngredientsByRecipe = `-- name: DeleteRecipeIngredientsByRecipe :exec
DELETE FROM recipe_ingredients
WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeIngredientsByRecipe(ctx context.Context, recipeID string) error {
	_, err := q.db.Exec(ctx, deleteRecipeIngredientsByRecipe, recipeID)
	return err
}

const getRecipeByID = `-- name: GetRecipeByID :one
SELECT id, user_id, name, notes, created_at, updated_at FROM recipe
WHERE id = $1 AND user_id = $2
`

type GetRecipeByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetRecipeByID(ctx context.Context, arg GetRecipeByIDParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeByID, arg.ID, arg.UserID)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeFoods = `-- name: GetRecipeFoods :many
SELECT ri.id,
       ri.food_id,
       ri.weight_g,
       ri.notes,
       f.name AS food_name,
       f.calories_100,
       f.protein_100,
       f.carbohydrates_100,
       f.fat_100
FROM recipe_ingredients ri
JOIN food f ON f.id = ri.food_id
JOIN recipe r ON r.id = ri.recipe_id
WHERE ri.recipe_id = $1::uuid
  AND r.user_id = $2::uuid
ORDER BY ri.created_at
`

type GetRecipeFoodsParams struct {
	RecipeID string `json:"recipe_id"`
	UserID   string `json:"user_id"`
}

type GetRecipeFoodsRow struct {
	ID               string      `json:"id"`
	FoodID           string      `json:"food_id"`
	WeightG          float64     `json:"weight_g"`
	Notes            pgtype.Text `json:"notes"`
	FoodName         string      `json:"food_name"`
	Calories100      float64     `json:"calories_100"`
	Protein100       float64     `json:"protein_100"`
	Carbohydrates100 float64     `json:"carbohydrates_100"`
	Fat100           float64     `json:"fat_100"`
}

func (q *Queries) GetRecipeFoods(ctx context.Context, arg GetRecipeFoodsParams) ([]GetRecipeFoodsRow, error) {
	rows, err := q.db.Query(ctx, getRecipeFoods, arg.RecipeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecipeFoodsRow
	for rows.Next() {
		var i GetRecipeFoodsRow
		if err := rows.Scan(
			&i.ID,
			&i.FoodID,
			&i.WeightG,
			&i.Notes,
			&i.FoodName,
			&i.Calories100,
			&i.Protein100,
			&i.Carbohydrates100,
			&i.Fat100,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT ri.id,
       ri.recipe_id,
       ri.food_id,
       ri.weight_g,
       ri.notes,
       f.name AS food_name,
       f.calories_100,
       f.protein_100,
       f.carbohydrates_100,
       f.fat_100
FROM recipe_ingredients ri
JOIN food f ON f.id = ri.food_id
WHERE ri.recipe_id = $1
ORDER BY ri.created_at
`

type ListRecipeIngredientsRow struct {
	ID               string      `json:"id"`
	RecipeID         string      `json:"recipe_id"`
	FoodID           string      `json:"food_id"`
	WeightG          float64     `json:"weight_g"`
	Notes            pgtype.Text `json:"notes"`
	FoodName         string      `json:"food_name"`
	Calories100      float64     `json:"calories_100"`
	Protein100       float64     `json:"protein_100"`
	Carbohydrates100 float64     `json:"carbohydrates_100"`
	Fat100           float64     `json:"fat_100"`
}

func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeID string) ([]ListRecipeIngredientsRow, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeIngredientsRow
	for rows.Next() {
		var i ListRecipeIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.FoodID,
			&i.WeightG,
			&i.Notes,
			&i.FoodName,
			&i.Calories100,
			&i.Protein100,
			&i.Carbohydrates100,
			&i.Fat100,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, user_id, name, notes, created_at, updated_at FROM recipe
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context, userID string) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, listRecipes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipe
SET name       = $3,
    notes      = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, notes, created_at, updated_at
`

type UpdateRecipeParams struct {
	ID     string      `json:"id"`
	UserID string      `json:"user_id"`
	Name   string      `json:"name"`
	Notes  pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Notes,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
