// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercise (workout_id, name, weight_kg, reps)
VALUES ($1, $2, $3, $4)
RETURNING id, workout_id, name, weight_kg, reps, created_at, updated_at
`

type CreateExerciseParams struct {
	WorkoutID string  `json:"workout_id"`
	Name      string  `json:"name"`
	WeightKg  float64 `json:"weight_kg"`
	Reps      int32   `json:"reps"`
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.WorkoutID,
		arg.Name,
		arg.WeightKg,
		arg.Reps,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.Name,
		&i.WeightKg,
		&i.Reps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workout (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateWorkoutParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRow(ctx, createWorkout, arg.UserID, arg.Name)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkoutRoutine = `-- name: CreateWorkoutRoutine :one
INSERT INTO workout_routine (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateWorkoutRoutineParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) CreateWorkoutRoutine(ctx context.Context, arg CreateWorkoutRoutineParams) (WorkoutRoutine, error) {
	row := q.db.QueryRow(ctx, createWorkoutRoutine, arg.UserID, arg.Name)
	var i WorkoutRoutine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkoutRoutineEntry = `-- name: CreateWorkoutRoutineEntry :one
INSERT INTO workout_routine_entries (workout_routine_id, name, weight_kg, reps)
VALUES ($1, $2, $3, $4)
RETURNING id, workout_routine_id, name, weight_kg, reps, created_at, updated_at
`

type CreateWorkoutRoutineEntryParams struct {
	WorkoutRoutineID string  `json:"workout_routine_id"`
	Name             string  `json:"name"`
	WeightKg         float64 `json:"weight_kg"`
	Reps             int32   `json:"reps"`
}

func (q *Queries) CreateWorkoutRoutineEntry(ctx context.Context, arg CreateWorkoutRoutineEntryParams) (WorkoutRoutineEntry, error) {
	row := q.db.QueryRow(ctx, createWorkoutRoutineEntry,
		arg.WorkoutRoutineID,
		arg.Name,
		arg.WeightKg,
		arg.Reps,
	)
	var i WorkoutRoutineEntry
	err := row.Scan(
		&i.ID,
		&i.WorkoutRoutineID,
		&i.Name,
		&i.WeightKg,
		&i.Reps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkout = `-- name: DeleteWorkout :execrows
WITH deleted_exercises AS (
    DELETE FROM exercise
    WHERE workout_id = $1::uuid
      AND EXISTS (
          SELECT 1 FROM workout w
          WHERE w.id = $1::uuid AND w.user_id = $2::uuid
      )
)
DELETE FROM workout
WHERE id = $1::uuid AND user_id = $2::uuid
`

type DeleteWorkoutParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteWorkout(ctx context.Context, arg DeleteWorkoutParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkout, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkoutRoutineByID = `-- name: GetWorkoutRoutineByID :one
SELECT id, user_id, name, created_at, updated_at FROM workout_routine
WHERE id = $1 AND user_id = $2
`

type GetWorkoutRoutineByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetWorkoutRoutineByID(ctx context.Context, arg GetWorkoutRoutineByIDParams) (WorkoutRoutine, error) {
	row := q.db.QueryRow(ctx, getWorkoutRoutineByID, arg.ID, arg.UserID)
	var i WorkoutRoutine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExercisesByWorkout = `-- name: ListExercisesByWorkout :many
SELECT id, workout_id, name, weight_kg, reps, created_at, updated_at FROM exercise
WHERE workout_id = $1
ORDER BY created_at
`

func (q *Queries) ListExercisesByWorkout(ctx context.Context, workoutID string) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercisesByWorkout, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutID,
			&i.Name,
			&i.WeightKg,
			&i.Reps,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutRoutineEntries = `-- name: ListWorkoutRoutineEntries :many
SELECT id, workout_routine_id, name, weight_kg, reps, created_at, updated_at FROM workout_routine_entries
WHERE workout_routine_id = $1
ORDER BY created_at
`

func (q *Queries) ListWorkoutRoutineEntries(ctx context.Context, workoutRoutineID string) ([]WorkoutRoutineEntry, error) {
	rows, err := q.db.Query(ctx, listWorkoutRoutineEntries, workoutRoutineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutRoutineEntry
	for rows.Next() {
		var i WorkoutRoutineEntry
		if err := rows.Scan(
			&i.ID,
			&i.WorkoutRoutineID,
			&i.Name,
			&i.WeightKg,
			&i.Reps,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutRoutines = `-- name: ListWorkoutRoutines :many
SELECT id, user_id, name, created_at, updated_at FROM workout_routine
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkoutRoutines(ctx context.Context, userID string) ([]WorkoutRoutine, error) {
	rows, err := q.db.Query(ctx, listWorkoutRoutines, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkoutRoutine
	for rows.Next() {
		var i WorkoutRoutine
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsByDate = `-- name: ListWorkoutsByDate :many
SELECT id, user_id, name, created_at, updated_at FROM workout
WHERE user_id = $1 AND created_at::date = $2::date
ORDER BY created_at DESC
`

type ListWorkoutsByDateParams struct {
	UserID  string      `json:"user_id"`
	Column2 pgtype.Date `json:"column_2"`
}

func (q *Queries) ListWorkoutsByDate(ctx context.Context, arg ListWorkoutsByDateParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, listWorkoutsByDate, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkoutsByDateRange = `-- name: ListWorkoutsByDateRange :many
SELECT id, user_id, name, created_at, updated_at FROM workout
WHERE user_id = $1
  AND created_at::date BETWEEN $2::date AND $3::date
ORDER BY created_at DESC
`

type ListWorkoutsByDateRangeParams struct {
	UserID   string      `json:"user_id"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

func (q *Queries) ListWorkoutsByDateRange(ctx context.Context, arg ListWorkoutsByDateRangeParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, listWorkoutsByDateRange, arg.UserID, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
